[package]
name = "tictactoe-rust"
version = "0.1.0"
authors = ["aventuracodes"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
